### ISSUE TITLE
Doens't load on paper 1.19.4

### ISSUE THREAD

**Issue by Tresillo2017** [xxCoderforlife/Simple-Drugs#44]
**Describe the bug**

**To Reproduce**
1. Download latest DEV build
2. Upload to plugin forlder
3. Start server

**Expected behavior**
To load and work

**Screenshots**
```
[16:51:43 INFO]: ============[Simple-Drugs]============
[16:51:43 INFO]: [SD] Starting up Simple-Drugs Version: 2.7.7-DEV
[16:51:44 INFO]: [SD] Vault has been found.
[16:51:44 INFO]: [SD] Hooked into Vault.
[16:51:44 INFO]: [SD] Found PlaceHolderAPI.
[16:51:44 INFO]: [PlaceholderAPI] Successfully registered expansion: drug [2.7]
[16:51:44 INFO]: [SD] Hooked into PlaceHolderAPI
[16:51:44 ERROR]: Error occurred while enabling Simple-Drugs v2.7.7-DEV (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null
        at me.Coderforlife.SimpleDrugs.Util.GsonAdapaters.DrugAdapter.deserialize(DrugAdapter.java:44) ~[Simple-Drugs-2.7.7-DEV.jar:?]
        at me.Coderforlife.SimpleDrugs.Util.GsonAdapaters.DrugAdapter.deserialize(DrugAdapter.java:22) ~[Simple-Drugs-2.7.7-DEV.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
        at me.Coderforlife.SimpleDrugs.Druging.DrugManager.createFromJson(DrugManager.java:75) ~[Simple-Drugs-2.7.7-DEV.jar:?]
        at me.Coderforlife.SimpleDrugs.Util.AbstractSDCraftableManager.loadFiles(AbstractSDCraftableManager.java:108) ~[Simple-Drugs-2.7.7-DEV.jar:?]
        at me.Coderforlife.SimpleDrugs.Setup.<init>(Setup.java:37) ~[Simple-Drugs-2.7.7-DEV.jar:?]
        at me.Coderforlife.SimpleDrugs.Main.onEnable(Main.java:92) ~[Simple-Drugs-2.7.7-DEV.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:51:44 INFO]: [SD] Disabling Simple-Drugs v2.7.7-DEV
```

- Plugin Version 2.7.7-DEV
- Server Version **1.19.4** and if **Paper**

**Additional context**
None

**Comment by xxCoderforlife** [comment]
@Tresillo2017 Have edited any of the configs?

**Comment by Tresillo2017** [comment]
```
# ========================[SIMPLE-DRUGS CONFIG]============================#
# Simple-Drugs v2.7-DEV Created by xxCoderforlife
# If you need help find me on Discord or Spigot.
# Spigot: https://www.spigotmc.org/resources/simple-drugs-with-gui.9684/
# Discord: https://discord.com/invite/jnmKj7Z
#               WIKI LINK: 
#    https://xxcoderforlife.gitbook.io/simpledrugswiki/
# =========================================================================#
Drugs:
  # If you want to even check for an update
  CheckForUpdate: true
  # If you want a message sent to players in game with the permission 'drugs.updater'
  UpdateMessage: false
  # Sends the player a plugin message on Join
  JoinMessage: true
  # Cooldown between Drug Usage in Seconds (Change to 0 to disable)
  Cooldown: 3
  BagOfDrugs:
    # If the player can move the bag in their Inventory
    CanMove: false
    # If the player can drop the bag
    CanDrop: false
    # Is the bag given on player join
    # If you set this to false use /drugs bagofdrugs to get it
    GiveOnJoin: true
    # If the Bag is dropped on death or not.
    DropOnDeath: false
    # If the player Keeps the Bag when they Respawn
    GiveOnRespawn: true
  Addiction:
    OverDose-Limit: 10.0
# Yeah that's the end of the Config.
```

This is what I have. I don't remember changing the config

**Comment by Tresillo2017** [comment]
Deleting the plugin folder worked
