### ISSUE TITLE
Error loading 2.6.8-alpha

### ISSUE THREAD

**Issue by iShowee** [xxCoderforlife/Simple-Drugs#8]
Log dump, running spigot 1.8.8

[Server thread/ERROR]: Error occurred while enabling SimpleDrugs v2.6.8-alpha (Is it up to date?)
java.lang.NoSuchFieldError: TROPICAL_FISH_BUCKET
	at me.Coderforlife.Drugs.CraftingCheck.<clinit>(CraftingCheck.java:21) ~[?:?]
	at me.Coderforlife.Drugs.Main.WeedRec(Main.java:85) ~[?:?]
	at me.Coderforlife.Drugs.Main.onEnable(Main.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by xxCoderforlife** [comment]
Please use the 1.8.8 version of Simple-Drugs

https://github.com/xxCoderforlife/Simple-Drugs/releases/tag/v1.0.0
